version: '3'

services:

  word2vec:
    build:
      context: .
    volumes:
      - ./word2vec:/src/word2vec
      - ./datasets:/datasets
      - ./tests:/tests
    ports:
      - 10001:9090
    environment:
    - W2V_SERVER_PORT=9090
    - W2V_VECTOR_FILE=/datasets/wiki.pt-test.vec
    #- W2V_VECTOR_FILE=/tests/data_test_embedding.txt
