version: '3'

services:

  word2vec:
    build:
      context: .
    volumes:
      - ./hu_w2v:/src/hu_w2v
      - ./datasets:/datasets
      - ./tests:/tests
    environment:
    - W2V_SERVER_PORT=9090
    # - W2V_VECTOR_FILE=/datasets/glove.840B.300d.txt
    - W2V_VECTOR_FILE=/tests/data_test_embedding.txt
